/**
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model

case class ReadRequest (
  /* The identifier of the agent that is requesting the read. */
  tag: String,
  time: Int,
  origin: Coordinates,
  /* A grid's length */
  length: Int,
  /* A grid's width */
  width: Int,
  /* Require to filter formulas when performing a read */
  filter_formulas: Boolean,
  /* Should the agent have no cell defined, read from this agent's sheet */
  default: String
)
